name: ex28-ghc-extensions-deriving
version: 0.1.0.0

library:
  source-dirs: src
  exposed-modules: Exercise
  default-extensions:
    - DerivingStrategies
    - GeneralizedNewtypeDeriving
    - DerivingVia
    - DeriveGeneric
    - DeriveTraversable
    - DeriveAnyClass
    - StandaloneDeriving
  dependencies:
    - base >= 4.17 && < 5

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    default-extensions:
      - DerivingStrategies
    dependencies:
      - base >= 4.17 && < 5
      - ex28-ghc-extensions-deriving
      - hspec >= 2.11
      - hspec-discover
      - QuickCheck
    build-tools:
      - hspec-discover:hspec-discover
