name: ex16-state-reader-writer
version: 0.1.0.0
dependencies:
  - base >= 4.17 && < 5
  - mtl >= 2.3

library:
  source-dirs: src
  exposed-modules:
    - Exercise

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - ex16-state-reader-writer
      - hspec >= 2.11
      - hspec-discover
      - QuickCheck
      - mtl >= 2.3
